import { useState } from "react";

const VIEW_LABELS = { dashboard: "Dashboard", kanban: "Kanban Board", gantt: "Gantt Chart", timer: "Theo dõi thời gian" };
const NOTIF_ICONS = { success: "ti-circle-check", info: "ti-info-circle", warning: "ti-alert-triangle", danger: "ti-alert-circle" };
export default function Topbar({ view, filterProject, projects, onAddTask, notifications, dismissNotification, clearAll }) {
  const [showNotifs, setShowNotifs] = useState(false);
  const proj = projects.find((p) => p.id === filterProject);
  const title = proj ? proj.name : VIEW_LABELS[view] || "FlowBoard";
  const unread = notifications.length;
  return (<><div className="topbar"><div className="topbar-title">{title}</div><button className="btn btn-sm" style={{ position: "relative" }} onClick={() => setShowNotifs((v) => !v)}><i className="ti ti-bell" aria-hidden="true" />{unread > 0 && (<span style={{ position: "absolute", top: -4, right: -4, background: "#E24B4A", color: "#fff", fontSize: 10, fontWeight: 500, borderRadius: "50%", width: 16, height: 16, display: "flex", alignItems: "center", justifyContent: "center" }}>{unread > 9 ? "9+" : unread}</span>)}</button><button className="btn btn-primary btn-sm" onClick={() => onAddTask()}><i className="ti ti-plus" aria-hidden="true" /> Thêm task</button></div>{showNotifs && (<div style={{ position: "absolute", top: "var(--topbar-h)", right: 16, width: 340, background: "var(--surface)", border: "0.5px solid var(--border)", borderRadius: "var(--radius-lg)", zIndex: 500, maxHeight: 400, overflow: "hidden", display: "flex", flexDirection: "column" }}><div style={{ padding: "12px 14px", borderBottom: "0.5px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between" }}><span style={{ fontSize: 13, fontWeight: 500 }}>Thông báo {unread > 0 && `(${unread})`}</span><div style={{ display: "flex", gap: 8 }}>{unread > 0 && <button className="btn btn-sm" onClick={clearAll} style={{ fontSize: 12 }}>Vóa tất cả</button>}<button className="icon-btn" onClick={() => setShowNotifs(false)}><i className="ti ti-x" aria-hidden="true" /></button></div></div><div style={{ overflowY: "auto", flex: 1 }}>{notifications.length === 0 ? (<div style={{ padding: "24px", textAlign: "center", color: "var(--text-3)", fontSize: 13 }}><i className="ti ti-bell-off" style={{ fontSize: 24, display: "block", marginBottom: 8 }} aria-hidden="true" />Không có thông báo</div>) : notifications.map((n) => (<div key={n.id} style={{ padding: "10px 14px", borderBottom: "0.5px solid var(--border)", display: "flex", gap: 10, alignItems: "flex-start" }}><i className={`ti ${NOTIF_ICONS[n.type] || "ti-bell"}`} style={{ fontSize: 16, marginTop: 1, color: n.type === "danger" ? "#A32D2D" : n.type === "warning" ? "#BA7517" : n.type === "success" ? "#3B6D11" : "#185FA5" }} aria-hidden="true" /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 500, color: "var(--text)", marginBottom: 2 }}>{n.title}</div>{n.message && <div style={{ fontSize: 12, color: "var(--text-2)", lineHeight: 1.4 }}>{n.message}</div>}</div><button className="icon-btn" onClick={() => dismissNotification(isame)} style={{ flexShrink: 0 }}><i className="ti ti-x" aria-hidden="true" /></button></div>))}</div></div>)}</>);}
